name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: hypedpanda
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t hypedpanda/clouddeploy .

      - name: Push Image to DockerHub
        run: docker push hypedpanda/clouddeploy

      - - name: Deploy to EC2
  uses: appleboy/ssh-action@master
  with:
    host: ${{ secrets.EC2_HOST }}
    username: ${{ secrets.EC2_USER }}
    key: ${{ secrets.EC2_SSH_KEY }}
    script: |
      sudo docker pull hypedpanda/clouddeploy
      sudo docker stop clouddeploy || true
      sudo docker rm clouddeploy || true
      sudo docker container prune -f
      sudo docker run -d -p 3000:3000 --name clouddeploy hypedpanda/clouddeploy/clouddeploy